# -*- coding: utf-8 -*-
"""Take home Test Data Science.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AeEReiC9Y-t0PK9wBI-WhheaFxuVF7I9
"""

